import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import api from '@/api/client'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { exportCsv } from '@/lib/utils'
import { useAuthStore } from '@/store/auth'

type Row={id:number;kind:string;fecha:string;cents:number;description:string|null;case_id:number|null;case_title:string|null;client_name:string|null;category_name:string|null;service_name:string|null;origen_negocio:string;url:string}
type Extra={portfolio:{id:number;title:string;estado_cobro:string;mes:string;balance:number;probability:number|null;weighted:number|null}[];portfolio_total:number;portfolio_weighted:number;missing_probability:number;frequency:{service_id:number|null;service:string;cases:{id:number;title:string}[]}[];profitability:{service:string;income:number;cost:number;profit:number;margin:number|null}[];goals:{id:number;mes:string;family_name:string;volumen_meta:number;ingreso_proyectado_cents:number}[];goals_supported:boolean;goal_income:number;goal_actual_income:number;goal_volume:number;actual_volume:number;projected:number|null;income_compliance:number|null;volume_compliance:number|null;quoted:number;won:number;conversion:number|null;opportunities:{id:number;estado:string}[]}
type Result={extra:Extra;options:Record<string,{value:string|number;label:string}[]>;rows:Row[];categories:{category_id:number|null;name:string;income:number;cost:number;expense:number;commission:number;fixed:number;operating_budget:number;operating_cash:number}[];totals:{income:number;cost:number;expense:number;commission:number;fixed:number;operating_budget:number;operating_cash:number;cases:number;ticket:number|null;days_average:number|null;measured:number;without_reference:number};days:{id:number;case_id:number|null;invoice_id:number|null;income_date:string;reference:string;days:number}[];shared_fixed:number;shared_expenses:number;allocation_rule:string;threshold:string}
const money=(n:number)=>new Intl.NumberFormat('es-SV',{style:'currency',currency:'USD'}).format(n/100)
const fields=[['category_id','Categoría'],['subcategory_id','Subcategoría'],['service_id','Servicio'],['family_id','Familia'],['client_id','Cliente'],['origen_negocio','Origen del negocio']] as const
export function FinancialExplorer(){
 const user=useAuthStore(s=>s.user);const can=(module:string)=>!!user&&(user.is_admin||user.permissions.includes(module+'.ver'))
 const [desde,setDesde]=useState(new Date().toISOString().slice(0,7)),[hasta,setHasta]=useState(desde)
 const [collectionState,setCollectionState]=useState('')
 const [filters,setFilters]=useState<Record<string,string>>({}),[kind,setKind]=useState('')
 const params={desde,hasta,...Object.fromEntries(Object.entries(filters).filter(([,v])=>v))}
 const {data,isLoading,isFetching,error}=useQuery({queryKey:['financial-explorer',params],placeholderData:previous=>previous,queryFn:()=>api.get<Result>('/finanzas/explorador',{params}).then(r=>r.data),enabled:!!desde&&!!hasta&&desde<=hasta})
 const rows=data?.rows.filter(r=>!kind||r.kind===kind)??[]
 const scoped=Object.values(filters).some(Boolean)
 const cards=data?[['Ingresos netos',money(data.totals.income),'Ingreso'],['Costos directos',money(data.totals.cost),'Costo directo'],['Gastos pagados',money(data.totals.expense),'Gasto operativo'],['Comisión devengada',money(data.totals.commission),'Comisión devengada'],['Gastos fijos presupuestados',money(data.totals.fixed),'Gasto fijo presupuestado'],[scoped?'Utilidad atribuible (presupuesto)':'Utilidad operativa (presupuesto)',money(data.totals.operating_budget),''],[scoped?'Resultado de caja atribuible':'Resultado operativo de caja',money(data.totals.operating_cash),''],['Ticket por expediente / operación',data.totals.ticket===null?'Sin cobros':money(data.totals.ticket),'Ingreso']]:[]
 return <section className="space-y-4"><h2 className="font-semibold">Explorador de indicadores y movimientos</h2><p className="text-sm text-muted-foreground">Todos los importes y detalles de esta vista usan los filtros seleccionados. Haz clic en una cifra para consultar sus movimientos.</p>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-3"><label className="text-xs">Desde<Input aria-label="Explorador desde" type="month" value={desde} onChange={e=>setDesde(e.target.value)}/></label><label className="text-xs">Hasta<Input aria-label="Explorador hasta" type="month" value={hasta} onChange={e=>setHasta(e.target.value)}/></label>{fields.map(([key,label])=><label key={key} className="text-xs">{label}<select aria-label={`Filtrar ${label}`} className="block w-full min-w-0 bg-background border rounded-md p-2 mt-1" value={filters[key]??''} onChange={e=>setFilters({...filters,[key]:e.target.value})}><option value="">Todos</option>{data?.options[key]?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>)}</div>
 <Button variant="outline" size="sm" onClick={()=>{setFilters({});setKind('')}}>Limpiar filtros</Button>
 {desde>hasta&&<p role="alert">La fecha inicial debe ser anterior a la final.</p>}{isLoading&&<p>Cargando indicadores…</p>}{isFetching&&!isLoading&&<p role="status" className="text-xs text-muted-foreground">Actualizando filtros…</p>}{error&&<p role="alert">No se pudieron cargar los indicadores.</p>}
 {data&&<><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3">{cards.map(([label,value,k])=><button key={label} onClick={()=>setKind(k)} className="border rounded-lg p-4 text-left"><p className="text-xs text-muted-foreground">{label}</p><strong className="text-xl">{value}</strong></button>)}</div>
 <p className="text-xs text-muted-foreground">Ticket = ingresos netos / {data.totals.cases} expedientes con cobro u operaciones sin expediente. Margen operativo presupuestado: {data.totals.income?(100*data.totals.operating_budget/data.totals.income).toFixed(1)+'%':'no calculable'} (utilidad / ingresos). Margen de caja = {money(data.totals.operating_cash)} / {money(data.totals.income)} = {data.totals.income?(100*data.totals.operating_cash/data.totals.income).toFixed(1)+'%':'no calculable'}.</p>
 <p className="text-sm">{scoped&&'Esta selección muestra el resultado atribuible; no representa una utilidad completa después de repartir gastos compartidos. '}{data.allocation_rule} Gastos compartidos del período completo (pagados / presupuestados): <strong>{money(data.shared_expenses)} / {money(data.shared_fixed)}</strong>.</p>
 <div className="overflow-x-auto border rounded-lg"><table className="w-full text-sm"><thead><tr>{['Categoría','Ingresos','Costos','Gastos pagados','Comisión devengada','Gasto fijo presup.','Utilidad operativa','Resultado de caja'].map(h=><th className="p-3 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{data.categories.map(r=><tr key={r.category_id??'shared'} className="border-t"><td className="p-3">{r.name}</td>{[r.income,r.cost,r.expense,r.commission,r.fixed,r.operating_budget,r.operating_cash].map((v,i)=><td className="p-3 whitespace-nowrap" key={i}>{money(v)}</td>)}</tr>)}</tbody></table></div>
 <details className="border rounded-lg p-3"><summary>Días de cobro: {data.totals.days_average??'—'} · {data.totals.measured} aplicaciones medidas · {data.totals.without_reference} sin referencia válida</summary><p className="text-xs my-2">Promedio simple por aplicación de cobro vigente. Los anticipos y registros sin factura o cierre no bajan artificialmente el promedio.</p><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th>Cobro</th><th>Factura / cierre</th><th>Fecha de pago</th><th>Días</th></tr></thead><tbody>{data.days.map((d,i)=><tr key={i}><td>#{d.id}</td><td>{d.reference}</td><td>{d.income_date}</td><td>{d.days}</td></tr>)}</tbody></table></div></details>
 <details className="border rounded-lg p-3"><summary>Metas, proyección y conversión</summary>
 <div className="space-y-3 mt-3 text-sm">
 {data.extra.goals_supported?<><p>Ingresos de las familias presupuestadas: {money(data.extra.goal_actual_income)} / meta {money(data.extra.goal_income)} · Cumplimiento: {data.extra.income_compliance===null?'Sin meta':(100*data.extra.income_compliance).toFixed(1)+'%'}.</p><p className="text-xs text-muted-foreground">Las metas y su cumplimiento se comparan por familia de la cuenta de ingreso. La categoría del servicio puede ser distinta; no se mezclan ambas clasificaciones.</p><p>Volumen: {data.extra.actual_volume} expedientes/operaciones cobrados por familia y mes / {data.extra.goal_volume} de meta = {data.extra.volume_compliance===null?'Sin meta':(100*data.extra.volume_compliance).toFixed(1)+'%'}.</p><p>Proyección comercial: {money(data.extra.projected??0)} = presupuesto + cartera ponderada. Solo es aditiva si el presupuesto representa negocio adicional.</p><ul>{data.extra.goals.map(g=><li key={g.id}>{g.mes} · {g.family_name}: {g.volumen_meta} casos · {money(g.ingreso_proyectado_cents)}</li>)}</ul></>:<p>Las metas solo admiten mes, familia y categoría. Quita los filtros de servicio, subcategoría, cliente u origen para compararlas.</p>}
 <p>Conversión: {data.extra.won} aceptadas / {data.extra.quoted} cotizadas = {data.extra.conversion===null?'Sin cotizaciones':(100*data.extra.conversion).toFixed(1)+'%'}. Cohorte por fecha de cotización.</p>
 {can('pipeline')&&<Link className="underline" to="/pipeline">Consultar las cotizaciones en Pipeline</Link>}
 </div></details>
 <details className="border rounded-lg p-3"><summary>Cartera por mes esperado: {money(data.extra.portfolio_total)} · Ponderada: {money(data.extra.portfolio_weighted)}</summary><p className="text-xs my-2">Los meses filtran la fecha esperada de cobro. La cartera es el saldo actual; {data.extra.missing_probability} expedientes no tienen probabilidad configurada y quedan fuera de la suma ponderada.</p>
 <label className="text-sm">Estado de cobro <select className="bg-background border rounded p-2" value={collectionState} onChange={e=>setCollectionState(e.target.value)}><option value="">Todos</option>{[...new Set(data.extra.portfolio.map(r=>r.estado_cobro))].map(v=><option key={v}>{v}</option>)}</select></label>
 <p className="text-sm my-2">Selección: {money(data.extra.portfolio.filter(r=>!collectionState||r.estado_cobro===collectionState).reduce((n,r)=>n+r.balance,0))} · Ponderada: {money(data.extra.portfolio.filter(r=>!collectionState||r.estado_cobro===collectionState).reduce((n,r)=>n+(r.weighted??0),0))}</p>
 <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th>Expediente</th><th>Mes</th><th>Saldo</th><th>Probabilidad</th><th>Ponderado</th></tr></thead><tbody>{data.extra.portfolio.filter(r=>!collectionState||r.estado_cobro===collectionState).map(r=><tr key={r.id}><td className="p-2">{can('expedientes')?<Link className="underline" to={`/cases?case_id=${r.id}`}>{r.title}</Link>:r.title}</td><td>{r.mes}</td><td>{money(r.balance)}</td><td>{r.probability===null?'Pendiente':(100*r.probability).toFixed(0)+'%'}</td><td>{r.weighted===null?'—':money(r.weighted)}</td></tr>)}</tbody></table></div></details>
 <details className="border rounded-lg p-3"><summary>Servicios: frecuencia y rentabilidad</summary><div className="grid gap-4 sm:grid-cols-2 mt-3"><div><h3 className="font-semibold text-sm">Expedientes abiertos en el período</h3>{data.extra.frequency.map((r,i)=><details key={i} className="text-sm py-2"><summary>{r.service}: {r.cases.length}</summary>{r.cases.map(c=><p key={c.id}>{can('expedientes')?<Link className="underline" to={`/cases?case_id=${c.id}`}>{c.title}</Link>:c.title}</p>)}</details>)}</div><div><h3 className="font-semibold text-sm">Utilidad directa de cobros del período</h3>{data.extra.profitability.map((r,i)=><p key={i} className="text-sm py-2">{r.service}: {money(r.profit)} = {money(r.income)} − {money(r.cost)} · Margen {r.margin===null?'—':(100*r.margin).toFixed(1)+'%'}</p>)}</div></div></details>
 <div className="flex flex-wrap gap-2 items-center"><h3 className="font-semibold">Movimientos · {kind||'Todos'}</h3><Button size="sm" variant="outline" onClick={()=>setKind('')}>Ver todos</Button><Button size="sm" variant="outline" onClick={()=>exportCsv('indicadores.csv',['Tipo','ID','Fecha','Expediente','Cliente','Categoría','Servicio','Origen','Importe neto'],rows.map(r=>[r.kind,r.id,r.fecha,r.case_title,r.client_name,r.category_name,r.service_name,r.origen_negocio,r.cents/100]))}>Exportar detalle</Button></div>
 <div className="overflow-x-auto border rounded-lg"><table className="w-full text-sm"><thead><tr>{['Tipo','Fecha','Expediente / concepto','Cliente','Neto'].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={`${r.kind}-${r.fecha}-${r.id}`} className="border-t"><td className="p-3">{r.kind} #{r.id}</td><td className="p-3 whitespace-nowrap">{r.fecha}</td><td className="p-3">{r.case_id&&can('expedientes')?<Link className="underline" to={r.url}>{r.case_title}</Link>:r.case_title||r.description||'Sin expediente'}</td><td className="p-3">{r.client_name||'—'}</td><td className="p-3 whitespace-nowrap">{money(r.cents)}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-4 text-muted-foreground">Sin movimientos con estos filtros.</p>}</div>
 <p className="text-xs text-muted-foreground">Semáforo general de metas: {data.threshold} Las metas se autorizan por familia y mes; no se distribuyen artificialmente por cliente o servicio.</p></>}
 </section>
}
